name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TARGET_FILE: "src/index.js"

jobs:
  fmt_build_greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run fmt_build_greet
        run: |
          npm install
          npx prettier --write ${TARGET_FILE}
          npm run build
          npm run greet
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply GitHub actions.
          ref: ${{ github.head_ref }}
